#!/bin/sh

rmset() {
  if eval "test -z \"\$$1\"" ; then
    eval "export $1='$2'"
  fi
}

rmecho() {
  echo "$@"
}
rmwarn() {
  echo "$@"
}

rmdie() {
  echo "$@" >&2
  if test "$RM_GUI" = "y" ; then
    (IFS=' '; yad $RM_GUIARGS --text "$@" --button 'OK!gtk-ok';)
  fi
  exit 1
}

rmdieL() {
  if test "$RM_GUI" = "y" ; then
    (IFS=' '; yad --text-info --filename="$1" --button 'OK!gtk-ok' $RM_GUIARGS ;)
  fi
  exit 1
}

rmcheck() {
  if test -d "$RME_XOCHITL" ; then
    rmdie "RM_XOCHITL($RM_XOCHITL) is not a dir"
  fi
}

rmdr() {
  if test -z "$RM_DRYRUN" ; then
    "$@"
  else
    echo "$@"
  fi
}

mkprogress() {
  # Create the progressbar
  test "$RM_GUI" = "y" || return 0
  d="$1"
  title="$2"
  test -d "$d" || return 1
  rm "$d/fifo" 2>/dev/null || true
  mkfifo "$d/fifo"
  (IFS=' '; yad $RM_GUIARGS --progress --title="$title" "$3" < "$d/fifo" &
    echo "$!" > "$d/yad.pid"
  )
  exec 5>"$d/fifo"
  RM_PF="5"
}

killprogress() {
  # Cleanup progressbar resources
  RM_PF="1"
  test "$RM_GUI" = "y" || return 0
  d="$1"
  test -d "$d" || return 1
  rm "$d/fifo" 2>/dev/null || true
  exec 5>&- || true
  kill $(cat "$d/yad.pid") 2>/dev/null
}

echoprogress() {(
  # Update the progressbar
  set +x
  # test "$RM_GUI" = "y" || return 0
  shift # T is not used
  READINP=y
  ADDNUMBERS=n
  while test -n "$1" ; do
    case "$1" in
      --add-numbers) ADDNUMBERS=y ;;
      [0-9]*|\#*) echo "$1" >&$RM_PF ; echo "$1"; READINP=n;;
      -) READINP=y ;;
      *) echo "#$1" >&$RM_PF; echo "$1"; READINP=n ;;
    esac
    shift
  done
  if test "$READINP" = "y" ; then
    i=0
    while read L ; do
      case $L in
        [0-9]*) echo $L >&$RM_PF ;;
        \#*)
          if test "$ADDNUMBERS" = "y"; then
            echo $i >&$RM_PF
          fi
          echo $L >&$RM_PF
        ;;
      esac
      echo $L
      i=$(expr $i '+' 1)
    done
  fi
)}

RM_NOUSER="<INVALID_USER>"
RM_NOIP="<INVALID_IP>"
RM_NOPORT="<INVALID_PORT>"

RM_PF=1
if test -f "$(dirname "$0")/rmconfig" ; then
  . $(dirname "$0")/rmconfig
fi

rmset RM_GUI "y"
rmset RM_VERBOSE "n"
rmset RM_DRYRUN ""
rmset RM_AMARKER "annot"

rmset RM_GUIARGS ""
rmset RM_XOCHITL $HOME/.xochitl
rmset RM_SSH remarkable
rmset RM_VPSSSH ""
rmset RM_VPSRPORT "$RM_NOPORT"

rmset RM_VPSIP "$RM_NOIP" # Optional
rmset RM_VPSUSER "$RM_NOUSER" # Optional
rmset RM_VPSPORT "$RM_NOPORT" # Optional
