#!/bin/sh

. $(dirname $0)/rmcommon

F=
CACHE=
while test -n "$1" ; do
  case "$1" in
    *)
    if test -z "$F" ; then
      F="$1"
    else
      CACHE="$F"
      F="$1"
    fi
    ;;
  esac
  shift
done

set -e -x

rmcheck

if ! test -f "$CACHE" ; then
  CACHE=/tmp/rmfind_$UID.txt
  rmls >$CACHE
fi

if test -f "$F" ; then
  FN=$(basename "$F" .pdf)
else
  FN="$F"
fi

grep --fixed-strings "$FN" "$CACHE" | awk '{print $1}'
