#!/bin/sh

. $(dirname $0)/rmcommon

while test -n "$1" ; do
  case "$1" in
    --gui) RM_GUI=y ;;
    --no-gui) RM_GUI=n ;;
    --dry-run) RM_DRYRUN='--dry-run' ;;
    -v|--verbose) RM_VERBOSE=y ;;
    -h|--help)
      echo "rmpush [--[no-]gui] [--dry-run] [-v|--verbose]" >&2;
      exit 1
      ;;
  esac
  shift
done

RSYNC_VERBOSE=""
if test "$RM_VERBOSE" = "y" ; then
  RSYNC_VERBOSE="-v"
  set -x
fi

set -e

rmcheck

T=$(mktemp -d --tmpdir)
LOG=$T/rmpull_$UID.txt
trap "killprogress '$T'; rm -rf '$T'" 0 1 2 3 9

{
mkprogress "$T" "Checking the connection" "--pulsate"
echoprogress "$T" -S 0 "Checking the connection"
while ! rmssh -o "ConnectTimeout=3" "$RM_SSH" /bin/true ; do
  echoprogress "$T" -S 100 "Checking the connection"
  sleep 0.1
done
killprogress "$T"

# mkprogress "$T" "Pulling from Remarkable" "--pulsate"
# echoprogress "$T" -S 0 "Pulling..."
# rsync --out-format='#Pulling: %n%L' $RSYNC_VERBOSE \
#   -i -aP $RM_DRYRUN -e "rmssh" \
#   "$RM_SSH:/home/root/.local/share/remarkable/xochitl/" "${RM_XOCHITL}/" | \
#   echoprogress "$T" --add-numbers
# killprogress "$T"

mkprogress "$T" "Pushing to Remarkable" "--pulsate"
# echoprogress "$T" -S 0 "Pushing..."
# rsync --out-format='#Pushing: %n%L ' $RSYNC_VERBOSE \
#   -i -aP $RM_DRYRUN --no-owner --no-group -e "rmssh" \
#   "${RM_XOCHITL}/" "$RM_SSH:/home/root/.local/share/remarkable/xochitl/" | \
#   echoprogress "$T" --add-numbers
rsync --out-format='- - %n' $RSYNC_VERBOSE \
  -i -aP $RM_DRYRUN --no-owner --no-group -e "rmssh" \
  --partial --progress --info=progress2 \
  "${RM_XOCHITL}/" "$RM_SSH:/home/root/.local/share/remarkable/xochitl/" \
  | awk '1;{fflush()}' RS='\r|\n' \
  | while read size percents rest ; do
    echo $size $percents $rest
    case "$percents" in
      -) F=$rest;;
      *%) echoprogress "$T" "$percents" "Pushing \"$F\"" ;;
    esac
  done

echoprogress "$T" "Restarting Remarkable GUI"
rmdr rmssh "$RM_SSH" systemctl restart xochitl
killprogress "$T"
echo y > $T/OK
} 2>&1 | tee -a "$LOG"


if ! grep -q -s y "$T/OK" ; then
  rmdieL "$LOG"
fi


