#!/bin/sh

. $(dirname $0)/rmcommon

INCLUDE_THUMBNAILS=n

while test -n "$1" ; do
  case "$1" in
    -D) RM_DEVICE=$2 ; shift ;;
    --gui) RM_GUI=y ;;
    --no-gui) RM_GUI=n ;;
    --dry-run) RM_DRYRUN='--dry-run' ;;
    --delete) RM_DELETE='--delete' ;;
    --include-thumbnails) INCLUDE_THUMBNAILS=y ;;
    -v|--verbose) RM_VERBOSE=y ;;
    -h|--help)
      echo "rmpull [-D (A|B)] [--[no-]gui] [--dry-run] [-v|--verbose] [--delete]" >&2;
      exit 1
      ;;
  esac
  shift
done

RSYNC_VERBOSE=""
if test "$RM_VERBOSE" = "y" ; then
  RSYNC_VERBOSE="-v"
  set -x
fi

set -e

rmcheck

T=$(mktemp -d --tmpdir)
LOG=$T/rmpull_$UID.txt
trap "killprogress '$T'; rm -rf '$T'" 0 1 2 3 9

echo >$T/exclude.files
if test "$INCLUDE_THUMBNAILS" = "n" ; then
  echo "*.thumbnails" >> $T/exclude.files
fi

{
mkprogress "$T" "Checking the connection" "--pulsate"
echoprogress "$T" -S 0 "Checking the connection"
while ! rmssh -o "ConnectTimeout=3" "$RM_SSH" /bin/true ; do
  echoprogress "$T" -S 100 "Checking the connection"
  sleep 0.1
done
killprogress "$T"

mkprogress "$T" "Pulling from Remarkable $RM_DEVICE"
echoprogress "$T" -S 0 "Pulling..."

do_rsync() {
  rsync --out-format='- - %n' \
    -i -a $RM_DELETE -e "rmssh" \
    --partial \
    --exclude-from=$T/exclude.files \
    "$RM_SSH:/home/root/.local/share/remarkable/xochitl/" "${RM_XOCHITL}/" \
    "$@"
}

I=0
NFILES=`do_rsync --dry-run | wc -l`
do_rsync $RM_DRYRUN $RSYNC_VERBOSE \
  | awk '1;{fflush()}' RS='\r|\n' \
  | while read a b file ; do
    case $a$b in
    --)
      P=$(awk "BEGIN{print ($I/$NFILES)*100}")
      echoprogress "$T" "$P" "Pulling \"$file\""
      I=$(expr $I '+' 1)
      ;;
    *)
      echo $a $b $file
      ;;
    esac
  done
killprogress "$T"
echo y >$T/OK
} 2>&1 | tee -a "$LOG"

if ! grep -q -s y "$T/OK" ; then
  rmdieL "$LOG"
fi

