#!/bin/sh

. $(dirname $0)/rmcommon

CMD=""
NCTO='-w 5'
SNAME=`basename $0`
SSHTOOL=""
LOG=""
case "$SNAME" in
  *rmssh*) SSHTOOL=ssh ;; # Assume also `.rmssh-wrapped`
  *rmscp*) SSHTOOL=scp ;;
  *) rmdie "Invalid scrip basename $SNAME" ;;
esac

while test -n "$1" ; do
  case "$1" in
    --gui) RM_GUI=y;;
    --no-gui) RM_GUI=n;;
    --no-vps) RM_VPSSSH='' ;;
    -D) RM_DEVICE="$2" ; shift ;;
    -v|--verbose) RM_VERBOSE=y ;;
    --no-timeout) NCTO='' ;;
    --log) LOG="$2"; shift ;;
    -h|--help)
      echo "$SNAME [-D (A|B)] [--no-timeout] [-v|--verbose] [--log FILE] SSH_ARGS..." >&2;
      exit 1
      ;;
    --) shift; break ;;
    *) CMD="$CMD $1" ;;
  esac
  shift
done

if test "$RM_VERBOSE" = "y" ; then
  set -x
fi

T=$(mktemp -d --tmpdir)
trap "rm -rf '$T'" 0 1 3 9

log() {
  if test -n "$LOG"; then
    tee -a $LOG
  else
    cat
  fi
}

(
  trap "exit 1" 2
  if test -n "$RM_VPSSSH" ; then
    VPSRPORT=`rmvpsrport`
    $SSHTOOL \
      -o "ProxyCommand ssh $RM_VPSSSH nc $NCTO 127.0.0.1 $VPSRPORT" \
      -o "User root" \
      -o "StrictHostKeyChecking=no" \
      $CMD "$@"
  else
    $SSHTOOL \
      -o "User root" \
      -o "StrictHostKeyChecking=no" \
      $CMD "$@"
  fi
  echo "$?" >$T/RET
) 2>&1 | log

RET=$(cat "$T/RET")
if test -n "$LOG" -a x$(cat "$T/RET") != "x0" ; then
  ( rmdieL "$LOG" "Failed to establish ssh connection, code $RET" ; )
fi

exit $RET
